### ISSUE TITLE
Something other than just active class

### ISSUE THREAD

**Issue by StommePoes** [Pearson-Higher-Ed/pagination#1]
...to show which button is active.

I'm thinking some tag like span in the button with pe-sr-only class to hide it visually.
```
<button class="active">
<span class="pe-sr-only">Active page: </span>
5
</button>
```

**Comment by nlkluth** [comment]
No PR meant this closed itself - feel free to close if this is enough :)

**Comment by StommePoes** [comment]
Ok for now, I assume internationalisation comes along later?
