### ISSUE TITLE
Single page being doubled

### ISSUE THREAD

**Issue by antelopeb** [Pearson-Higher-Ed/pagination#15]
When there is only one page passed into the pagination component, it is showing the same page twice.
![image](https://user-images.githubusercontent.com/1117763/53111285-0ad96b00-34fa-11e9-91c9-36561adff2d0.png)

**Comment by shashwat5** [comment]
@antelopeb any ETA for the fix?
here is a jsfiddle if it helps: https://jsfiddle.net/0aej58c9/1/

**Comment by antelopeb** [comment]
@davodey -- Hey Dave, can you pick this up and toss out a fix?

**Comment by davodey** [comment]
Fixed and released as 1.1.1
